### ISSUE TITLE
Gaps in shipped logs to Scalyr

### ISSUE THREAD

**Issue by chen-anders** [zalando-incubator/kubernetes-log-watcher#31]
There have been times where I've found logs for pods through the kubernetes dashboard UI or `kubectl logs` that have not been shipped to over to Scalyr even though more recent log lines of that instance made it up without an issue. 

There seems to be no problems during idling behaviour of pods, but when things get busy - it seems like things do get missed.

**Comment by mohabusama** [comment]
Hi @chen-anders ,

Do you see log lines in Scalyr UI that look like this?

``skipped writing X log lines due to log rate limit``

**Comment by chen-anders** [comment]
I was not able to find anything along the lines of a log rate limit being hit in the Scalyr UI.

**Comment by mohabusama** [comment]
@chen-anders I am looking into some issues with regard to how scalyr/log-watcher handle logs. Right now, first thing I noticed is that using ``ConfigMap`` causes an issue of reseting the scalyr configuration (ending up with empty log targets). I am looking into Kubernetes setup alternatives along with testing the latest scalyr agent (with ``copy_from_start`` option)
