### ISSUE TITLE
Add support for custom Scalyr server

### ISSUE THREAD

**Issue by mohabusama** [zalando-incubator/kubernetes-log-watcher#35]
In Scalyr config:

``"scalyr_server": "https://custom-scalyr-server"``

**Comment by linki** [comment]
@mohabusama is this done? Seems like as https://github.com/zalando-incubator/kubernetes-on-aws/issues/654 was closed.

**Comment by mohabusama** [comment]
@linki Yeah, we can close this one since it is just a generic config that can be set via Kubernetes manifest and not really related to the log-watcher

**Comment by mohabusama** [comment]
Implementation in #53
