### ISSUE TITLE
Add Contributing guidelines

### ISSUE THREAD

**Issue by mohabusama** [zalando-incubator/kubernetes-log-watcher#47]
Add Contributing guidelines

**Comment by LappleApple** [comment]
Hi all: Wondering when this might happen. Could be a simple fork-and-merge; LMK if that's an option, or if you require special guidelines.

**Comment by mohabusama** [comment]
@LappleApple we don't require any guidelines

**Comment by mohabusama** [comment]
Will add one now. Thanks for bringing it up @LappleApple 😄

**Comment by LappleApple** [comment]
+1 @mohabusama
