### ISSUE TITLE
Making required labels configureable

### ISSUE THREAD

**Issue by eicnix** [zalando-incubator/kubernetes-log-watcher#63]
We are evaluating the kubernetes-log-watcher but our label structure doesn't match `application` and `version`.   
Therefore I would like to tackle this todo: `Support extending (overriding) constraints (e.g. require application, version and build labels to monitor the container)`

Is backwards compatibility necessary? Otherwise I would reuse the existing `WATCHER_STRICT_LABELS` environment variable to enable providing list of labels that need to be set so the pod will be monitored. 

example: `WATCHER_STRICT_LABELS: application,application`

**Comment by mohabusama** [comment]
Hi @eicnix

I agree that it makes sense ``WATCHER_STRICT_LABELS`` can be re-used to introduce a comma-separated list of required pod labels.

Would you be willing to contribute such change?

**Comment by eicnix** [comment]
Hi @mohabusama ,

I'd contribute this change and create a PR over the next days.

**Comment by mohabusama** [comment]
Awesome! Thanks @eicnix

**Comment by mohabusama** [comment]
@eicnix Released in [0.20](https://github.com/zalando-incubator/kubernetes-log-watcher/releases/tag/0.20)

Docker image: registry.opensource.zalan.do/eagleeye/kubernetes-log-watcher:0.20

**Comment by eicnix** [comment]
:+1:
